/**
 * Ontology identifier allowlists and surrogate keys for the graph tier (MEM-33).
 *
 * This module replaces the hand-rolled Cypher escaper that MEM-30 shipped.
 * sparrowdb 0.1.24 added `executeWithParams(cypher, params)` with working
 * parameterized `CREATE`, so **no value is ever interpolated into a query
 * again** — values travel as bound parameters and are stored inert. Writing
 * and maintaining an escaper for a Cypher dialect we do not control was a
 * liability we no longer need to carry, so it is gone rather than kept "just
 * in case": an unused security helper is one someone reaches for later.
 *
 * What still cannot be bound, and therefore still needs guarding:
 *
 *   - **Labels and relationship types.** `MATCH (n:$lbl)` is rejected outright
 *     (`expected label/type name, got Param("lbl")`), so labels must be
 *     literal text in the query. They come from our own closed ontology, so
 *     they are checked against an *allowlist of the exact ontology members* —
 *     not a character-class pattern. An allowlist of four labels cannot be
 *     talked into accepting a fifth; a regex can be argued with.
 *   - **Property keys.** Same story: a key is a syntactic position, not a
 *     value. Every key the adapter writes or projects is enumerated here.
 *   - **Edge endpoints.** Verified against 0.1.24: parameterized
 *     `MATCH (a:L {k: $v}), (b:L2 {k: $w}) CREATE (a)-[:R]->(b)` **silently
 *     creates nothing** — no error, no edge — and the `MERGE` form raises
 *     `parameterized MATCH...MERGE relationship ... not yet supported`. So an
 *     edge write cannot select its endpoints with bound parameters at all.
 *     Rather than reintroduce an escaper for endpoint values, endpoints are
 *     pinned by {@link surrogateId}: a SHA-256 digest *we* compute from the
 *     node's identity. It is 32 hex characters by construction, so
 *     interpolating it is not "escaping untrusted input" — there is no
 *     untrusted input in it. {@link assertSurrogateId} enforces that shape at
 *     the point of use, so a future refactor cannot quietly widen it.
 *
 * The net effect: every string that reaches a Cypher statement is either a
 * member of a closed set defined in this file, or a hex digest generated by
 * this file. Everything else is a bound parameter.
 */

import { EDGE_TYPES, NODE_LABELS, type EdgeType, type NodeLabel } from './graph-types.js';
import { createHash } from 'node:crypto';

/** Thrown when an identifier is not a member of the ontology. */
export class GraphIdentifierError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'GraphIdentifierError';
  }
}

/**
 * Every property key the adapter is allowed to write or project.
 *
 * Kept explicit rather than derived, because a key reaching a query is a
 * syntactic position: the cost of listing them is one line per property, and
 * the benefit is that an unlisted key is a loud error instead of raw text in a
 * statement.
 *
 * `zid` is the surrogate identity key (see {@link surrogateId}). Property names
 * are unique across the whole ontology, not merely per label — sparrowdb
 * resolves a projected property by name rather than by the pattern variable it
 * was qualified with, which is also why the `RELATES_TO` edge property is
 * `relKind` and not `kind`.
 */
export const PROPERTY_KEYS = [
  'zid',
  'name',
  'kind',
  'jobId',
  'summary',
  'outcome',
  'rationale',
  'signature',
  'tool',
  'hint',
  'ts',
  'relKind',
] as const;
export type PropertyKey = (typeof PROPERTY_KEYS)[number];

const LABELS = new Set<string>(NODE_LABELS);
const TYPES = new Set<string>(EDGE_TYPES);
const KEYS = new Set<string>(PROPERTY_KEYS);

/** A surrogate id is exactly 32 lowercase hex characters. Nothing else. */
const SURROGATE_PATTERN = /^[0-9a-f]{32}$/;

/**
 * Assert that `label` is one of the ontology's node labels.
 *
 * @returns The label, narrowed to {@link NodeLabel}.
 */
export function assertNodeLabel(label: unknown): NodeLabel {
  if (typeof label !== 'string' || !LABELS.has(label)) {
    throw new GraphIdentifierError(
      `Unknown node label ${JSON.stringify(label)}; expected one of: ${NODE_LABELS.join(', ')}`,
    );
  }
  return label as NodeLabel;
}

/**
 * Assert that `type` is one of the ontology's relationship types.
 *
 * @returns The type, narrowed to {@link EdgeType}.
 */
export function assertEdgeType(type: unknown): EdgeType {
  if (typeof type !== 'string' || !TYPES.has(type)) {
    throw new GraphIdentifierError(
      `Unknown relationship type ${JSON.stringify(type)}; expected one of: ${EDGE_TYPES.join(', ')}`,
    );
  }
  return type as EdgeType;
}

/**
 * Assert that `key` is a property key the ontology defines.
 *
 * @returns The key, narrowed to {@link PropertyKey}.
 */
export function assertPropertyKey(key: unknown): PropertyKey {
  if (typeof key !== 'string' || !KEYS.has(key)) {
    throw new GraphIdentifierError(
      `Unknown property key ${JSON.stringify(key)}; expected one of: ${PROPERTY_KEYS.join(', ')}`,
    );
  }
  return key as PropertyKey;
}

/**
 * Assert that `id` has the surrogate-key shape before it is interpolated.
 *
 * This is the guard that lets edge writes interpolate an endpoint selector at
 * all. It is not sanitisation — a value that fails this check is a bug in the
 * caller, not hostile input that needs cleaning — so it throws rather than
 * repairing.
 */
export function assertSurrogateId(id: unknown): string {
  if (typeof id !== 'string' || !SURROGATE_PATTERN.test(id)) {
    throw new GraphIdentifierError(
      `Invalid surrogate id ${JSON.stringify(id)}; expected 32 lowercase hex characters`,
    );
  }
  return id;
}

/**
 * Derive a node's surrogate identity key.
 *
 * Deterministic in `(label, identityKey, identityValue)`, so the same logical
 * node always maps to the same `zid` and an edge write can find its endpoints
 * without ever mentioning their real property values. The NUL separators keep
 * the three components unambiguous, so `('Task', 'jobId', 'ab')` and
 * `('Task', 'jobIdab', '')` cannot collide.
 *
 * 128 bits of SHA-256 is far beyond what a personal-scale graph needs to avoid
 * accidental collision, and the input is not adversarially chosen *against the
 * digest* — an attacker who could force a collision would only be able to make
 * two memory entities share a node.
 */
export function surrogateId(label: string, identityKey: string, identityValue: string): string {
  const l = assertNodeLabel(label);
  const k = assertPropertyKey(identityKey);
  return createHash('sha256').update([l, k, identityValue].join('\u0000')).digest('hex').slice(0, 32);
}
